# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

# Check that code style is black
- job: Black
  displayName: Black Code Style

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      pip install black
      black --check .
    displayName: 'Black'

# Run tests in each environment
- template: azure-pipelines-tox.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'
#
#
#- template: azure-pipelines-tox.yml
#  parameters:
#    name: MacOS
#    vmImage: 'macOS-10.13'
#
#
#- template: azure-pipelines-tox.yml
#  parameters:
#    name: Windows
#    vmImage: 'vs2017-win2016'


#    - script: codecov --required --token=$(codecov.token)
#      condition: succeeded()
#      displayName: 'Codecov'