# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

strategy:
  matrix:
#    Python27:
#      python.version: '2.7'
#    Python35:
#      python.version: '3.5'
#    Python36:
#      python.version: '3.6'
    Python37:
      python.version: '3.7'
  maxParallel: 1

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip codecov pytest coverage
      python -m pip install .[tests]
    displayName: 'Install distribution & requirements'

  - script: pytest tests
    condition: succeeded()
    displayName: 'Pytest'

  - script: coverage run -m pytest tests
    condition: succeeded()
    displayName: 'Coverage'

  - script: codecov --required --token=$(codecov.token)
    condition: succeeded()
    displayName: 'Codecov'
