# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

# Check that code style is black
- job: Black
  displayName: Black Code Style

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      pip install black
      black --check .
    displayName: 'Black'

# Run tests in each environment
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure-pipelines-tox.yml  # Template reference
